### ISSUE TITLE
关闭登录验证码配置页面会报错

### ISSUE THREAD

**Issue by xpwsgg** [hsk99/webman-admin#1]
![image](https://user-images.githubusercontent.com/20263865/164160605-68fb07f5-1ea1-4455-9e26-7373713004c2.png)

应该是在写入配置的时候使用empty判断0导致改配置被跳过了

**Comment by hsk99** [comment]
> ![图片](https://user-images.githubusercontent.com/20263865/164160605-68fb07f5-1ea1-4455-9e26-7373713004c2.png)
> 
> 应该是在写入配置的时候使用空判断0导致改配置被忽略了

版本 [1.0.2](https://github.com/hsk99/webman-admin/releases/tag/1.0.2) 已修复
